version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../mnist_model_split.npz:/app/mnist_model_split.npz
      - ../model_params.json:/app/model_params.json
